spring:
  application:
    name: LinkedinProfileExtractor


server:
  port: 8080

linkedin:
  base-url: ${LINKEDIN_BASE_URL}
  api-token: ${LINKEDIN_API_TOKEN}
  profile-endpoint: ${LINKEDIN_PROFILE_ENDPOINT:}