spring:
  application:
    name: LinkedinProfileExtractor


server:
  port: 8080

linkedin:
  # Voyager API (internal LinkedIn web API)
  voyager-base-url: https://www.linkedin.com
  profile-decoration-id: com.linkedin.voyager.dash.deco.identity.profile.FullProfileWithEntities-93